version: '3.8'
services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Admin123456
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - sqlnet
volumes:
  sql-server-data:
    name: sql-data
networks:
  sqlnet:
